const dictionnaire = {
  "a": "Jacob, Usher, Aaron",
  "aller": "yi",
  "ami": "hɔlɔ̃",
  "amour": "lɔlɔ̃",
  "apprendre": "srɔ̃",
  "arbre": "ati",
  "au revoir": "miadogo",
  "banane": "akɖu",
  "beau": "nyui",
  "boire": "no",
  "bon": "nyuie",
  "bonjour": "nzɔ",
  "chaise": "zikpui",
  "chat": "asevi",
  "chien": "avũ",
  "cinq": "atɔ̃",
  "comment": "aleke",
  "corps": "ŋtilã",
  "deux": "eve",
  "dieu": "mawu",
  "dix": "ewo",
  "donner": "na",
  "eau": "esi",
  "eau chaude": "esi xɔ",
  "eau froide": "esi fafá",
  "eau potable": "esi dodomé",
  "ecrire": "ŋlɔ",
  "el-haj": "femelle",
  "enfant": "vi",
  "famille": "pome",
  "femme": "nyɔnu",
  "fenêtre": "fesita",
  "feu": "dzó",
  "force": "ŋusẽ",
  "grand": "gã",
  "homme": "ŋutsu",
  "huit": "enyi",
  "jour": "ŋkeke",
  "lent": "blewu",
  "les séries mina lingo": "Mina – Vocabulaire de Base - © 2020 Delali Idrissou Page 1",
  "livre": "agbalẽ",
  "lune": "wòetrí",
  "main": "alɔ",
  "maison": "ahoe",
  "manger": "ɖu",
  "marché": "asigame",
  "matin": "ŋdi",
  "mauvais": "vɔ̃",
  "maïs": "ebli",
  "merci": "akpé",
  "mère": "enɔ",
  "neuf": "asike",
  "non": "ao",
  "nourriture": "nuɖuɖu",
  "nuit": "ezã",
  "oui": "ɛ̃",
  "paix": "nutifafa",
  "parler": "ƒo",
  "petit": "viɖe",
  "pied": "afɔ",
  "pluie": "tsi",
  "poisson": "akpavi",
  "porte": "agbɔ",
  "poule": "koklo",
  "prendre": "xɔ",
  "père": "etɔ",
  "quatre": "ene",
  "rapide": "kabakaba",
  "regarder": "kpɔ",
  "riz": "mɔlu",
  "route": "mɔ",
  "route principale": "mɔgã",
  "sept": "adré",
  "six": "ade",
  "soir": "fiẽ",
  "soleil": "ŋdɔkusu",
  "stylo": "biro",
  "table": "kplɔ",
  "temps": "ga",
  "travail": "edɔ",
  "trois": "etɔ̃",
  "tête": "eta",
  "un": "ɖeka",
  "venir": "va",
  "vent": "ya",
  "viande": "elã",
  "village": "duvi",
  "ville": "du",
  "visage": "ŋkume",
  "école": "suku",
  "écouter": "se"
};
